repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml

-   repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
    -   id: blue
        args: ["--check", "--diff"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile=black", "--line-length=79", "--check", "--diff"]
    