name: Relatar Bug
description: Relatar comportamento incorreto
title: "fix: "
labels: [fix, needs triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Pesquisa
      options:
        - label: Verifiquei se esse bug ainda não foi relatado.
          required: true
        - label: Verifiquei se esse bug existe na versão mais recente.
          required: true
        - label: Verifiquei se esse bug existe no branch main.
  - type: textarea
    id: example
    attributes:
      label: Exemplo reproduzível
      description: >
        Forneça um exemplo mínimo que pode ser copiado e colado para reproduzir 
        o erro.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Descrição do bug
      description: >
        Forneça uma descrição do bug mostrado no exemplo reproduzível.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento esperado
      description: >
        Descreva ou mostre um exemplo de código do comportamento esperado.
    validations:
      required: true