name: Pull Request Checker
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-check-title:
    runs-on: ubuntu-latest
    steps:
    - name : Check PR title validity
      run: |
        echo "${{ github.event.pull_request.title }}" | grep -E "(?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$"
        if [ $? -ne 0 ]; then
        echo "pull request title validation: failed!"
        echo "please enter a pull request title in the commitizen format"
        echo "pattern: (?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  test:
    uses: ./.github/workflows/test.yaml